### PR TITLE
feat(invite) find users and send mail

### PR DESCRIPTION
**Pull request by Onnassiz**
-setup api endpoint for finding users
-setup api endpoint for sending email to users
-create a nodemailer function for sending email
-create an email and url validator
-write test cases for finding players and sending email
-modify angular game controller
-added validation to search field by creating a directive
-styled text field and buttons
-etc

[#158457036]

### CODE REVIEW

**Comment by ikenjoku** [comment]
Well done Ben for raising the PR, I see you wrote readable code with clearly thought out logic and testing. However, I think you could do better to line up with the conventions of the codebase (i.e use either ES6 or ES5) because world-class developers can adapt their skills to line up to different style guides and team conventions.
I see you took the effort to comment on some of your code functions, but It is important to comment all the functions to help you and your reviewers understand the codebase.
Going forward, I challenge you to ensure you to line up with the conventions of your codebase and team. Build upon these and grow to deliver more excellent products.

**Comment by Onnassiz** [comment]
Thank you @ikenjoku for the pointing out those. I will put your recommendation into practice.

**Comment by ikenjoku** [comment]
I have not seen anywhere in the world where you write code like this. The codebase is not very nice and needs serious work. Please fix the codebase and resubmit.

**Comment by Onnassiz** [comment]
Thanks, @ikenjoku for your review. Can you please tell me where in the codebase you think needs serious work? Can you also explain to me the exact problem with the codebase so I can take necessary actions on your review?

**Pull request merged**
